version: "3.9"

services:
  billamusicbot:
    build: .
    image: billamusic:${TAG}
    container_name: billamusicbot
    network_mode: host
    pull_policy: never
  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 18000; docker restart billamusicbot; done"]
    restart: unless-stopped
    network_mode: host

networks:
  default: 
    external: true
    name: host
